---
# tasks for datadog-check-lynis

- name: "copy lynis check"
  copy:
    src: "files/checks.d/lynis.py"
    dest: "{{ ddagent_config_dir }}/checks.d/lynis.py"
    owner: "{{ ddagent_user }}"
    group: "{{ ddagent_group }}"
    mode: 0640

- name: copy check example configuration
  copy:
    src: "files/conf.d/lynis.yaml.example"
    dest: "{{ ddagent_config_dir }}/conf.d/lynis.yaml.example"
    owner: "{{ ddagent_user }}"
    group: "{{ ddagent_group }}"
    mode: 0640
